- name: create project directory
  ansible.builtin.file:
    name: "{{ folder }}/"
    state: directory
  tags:
    - deploy

- name: deploy python app
  block:
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: pull the image
      docker_image:
        name: "{{ image }}"
        source: pull
        state: present

    - name: create docker-compose file
      template:
        src: docker-compose.yml.j2
        dest: "{{ folder }}/docker-compose.yml"

    - name: run the container
      community.docker.docker_compose_v2:
        files:
          - "{{ folder }}/docker-compose.yml"
        project_src: "{{ folder }}/"
  tags:
    - deploy

- name: wipe python app
  import_tasks: wipe.yml
  when: web_app_full_wipe == true
  tags: 
    - wipe