name: flask-app

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install -r app_python/requirements.txt

    - name: Lint code
      run: |
        python -m pip install flake8
        flake8 .

    - name: Run tests
      run: pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t vectorsmaster/flask-app:latest ./python_app
        docker push vectorsmaster/flask-app:latest
